### ISSUE TITLE
SearchPageResponse does not fill `query` field

### ISSUE THREAD

**Issue by clorenz** [dbmdz/digitalcollections-model#215]
It must be filled manually with `setQuery(String query)`, although in the 3 parameter constructor, we have access to the `SearchPageRequest` object and thus to the query string.

It would be far more convenient to use this data to auto-fill the `query` field

**Comment by datazuul** [comment]
that was by intention: the query param in the response might be changed (e.g. normalized) before searching with search term of searchrequest.
the changed searchterm is returned to present the user which searchterm in the end was used.

**Comment by datazuul** [comment]
set/get query will be removed (deprectaed). use query field of contained SearchPageRequest instead
